### ISSUE TITLE
Create a LICENSE.md file

### ISSUE THREAD

**Issue by ktsamis** [romie-gr/romie#3]
I propose [Apache 2.0](https://opensource.org/licenses/Apache-2.0) just for fun

**Comment by cerebrux** [comment]
Choosing a license is really important as : 

- People will contribute with code, documentation etc
- People will download and distribute the code
- People will create derivatives 

So we have to answer the following questions:

1. What licenses are already (or will be) in use in my open source software ? (e.g. what license are the external libs that we need to incorporate and do not want to write our own)
2. What are the terms of service where my open source software is hosted? (Github, Dockerhub, brew)
3. Do I want derivatives, additions and distributions to use the same license? (If yes then Copyleft License, else Permissive)
4. Can others use my open source software in their own proprietary software?(If yes then Weak-Copyleft, else Strong-Copyleft)
 
### Popular (OSI-Approved) Licenses

|Strong-copyleft|Weak-copyleft|Permissive|
| ---|---|---|
|GPL|LGPL|MIT|
|Eclipse|Mozilla Public License 2.0|Apache 2.0|

Resources:

- [tldrleagal.com](tldrleagal.com)
- [choosealicense.com](https://choosealicense.com/)

**Comment by drpaneas** [comment]
I would be in favour of GPL-3

PS: Please put thumbs up if you like it.
PS: If not, please comment with your preferable option below.

**Comment by cerebrux** [comment]
> I would be in favour of GPL-3
> 
> PS: Please put thumbs up if you like it.
> PS: If not, please comment with your preferable option below.

Let's put it as a topic for our next meeting and hopefully everybody will have a strong opinion on what license is appropriate for our code :)

**Comment by cerebrux** [comment]
Another way of looking at it is that you’re picking a license based on what you are afraid of. 

1. All of these licenses assume you’re afraid of being sued.

2. The MIT license is if you’re afraid no one will use your code; you’re making the licensing as short and non-intimidating as possible. 

3. The Apache License you are somewhat afraid of no one using your code, but you are also afraid of legal ambiguity and patent trolls. 

4. With the GPL licenses, you are afraid of someone else profiting from your work and not giving back at least the changes to the original code (and ambiguity, and patent trolls). 

This is a radical simplification, but if nothing else it can be a helpful framework in discussing what license makes sense for your software

I'm currently in favor of Apache because it sits in the middle, just a step before becoming GPL3.

I'll send a PR once I read a little more on the matter.
